name: pi-player # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git #'0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Turns your device into a basic media player. # 79 char long summary
description: |
  pi-player is a web-based video, image and sound player written in go. Requires Chromium.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  pi-player:
    plugin: go
    go-channel: stable
    # we need gcc to run the CGO things to read keyboard input.
    build-packages:
      - gcc
    source: https://github.com/17xande/pi-player
    source-type: git
    source-depth: 1
    go-importpath: github.com/17xande/pi-player

    filesets:
      static:
      - "../src/pkg/piplayer/templates/*"
      - "../src/pkg/piplayer/assets/css/*"
      - "../src/pkg/piplayer/assets/js/*"

    prime:
      - "$static"

apps:
  pi-player:
    command: pi-player
